### ISSUE TITLE
Report Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wudapeng268** [thunlp/JointNRE#1]
hi, everyone
Can you write a readme for run your code?  I run `sh make.sh` in root, and then run `python JointD.py` but got "Segmentation fault (core dumped)". how to fix it?

thanks!

**Comment by THUCSTHanxu13** [comment]
Because there are no datasets in the toolkit. The data is big and can not be pushed directly into this toolkit. I will release these data in another way as soon as possible.

**Comment by THUCSTHanxu13** [comment]
I have released the code and dataset for the task RE. It is easy to deploy now. I also do some optimizations to make the framework run fast. You can have a try.
