### ISSUE TITLE
关于论文里面(16)式的说明

### ISSUE THREAD

**Issue by WeiyangZhang** [thunlp/JointNRE#13]
论文里面(16)式的说明中，您的论文提到了M_r是来自(12)式的M，但实际上，根据您的上下文语义，我理解的$$M_r$$应该是来自(15)式的M，此处是否有误

**Comment by THUCSTHanxu13** [comment]
对于文本模型来说关系分类其实就是将输出向量和M中每个关系对应的向量点乘然后softmax概率归一化。
(12)和(15)的M是一样的，就是文本空间中若干句子得到统一输出向量在预测关系分类时用的每个关系的计算向量。(12)式是sentence-level的式子，(15)是bug-level的式子，大概是这样 : )

**Comment by WeiyangZhang** [comment]
谢谢您的回复！

**Comment by THUCSTHanxu13** [comment]
没事~
