### ISSUE TITLE
关于 JointE 中测试代码的问题

### ISSUE THREAD

**Issue by wudapeng268** [thunlp/JointNRE#16]
Hi

感谢你的工作，我对 JointE/test.py line 132 有些疑问，在代码中您只是遍历了测试集中的整数 batch 的数据，那么剩下的那些数据好像并没有统计。我尝试着自己修改了一下代码，但是 scope 的维度和 label 的维度不匹配导致没有办法执行。。

祝好

**Comment by THUCSTHanxu13** [comment]
测试的时候，我们的batch_size是262，总个数是262的倍数，是可以整除的。如果你要用你自己的数据的话，batch_size要调整成你自己数据的总个数的某个约数。

**Comment by wudapeng268** [comment]
谢谢你的回答。
