### ISSUE TITLE
关于dataset的问题

### ISSUE THREAD

**Issue by lileilai** [thunlp/JointNRE#5]
韩旭, 您好：
       最近看到你的论文"Neural Knowledge Acquisition via Mutual Attention between Knowledge Graph and Text"，请问论文中提到的NYT-FB15K和NYT-FB15K-237这两个数据集能提供一下能下载的地址吗？非常感谢....

**Comment by THUCSTHanxu13** [comment]
FB15K和FB15K-237网上都能下载到
文本的话https://catalog.ldc.upenn.edu/LDC2008T19，
我是直接用wikidata的entity anchor名字来匹配的，
这个数据我没法授权，你想办法在这个LDC搞一下吧。。。
