### ISSUE TITLE
Some fixes related to flags' type in test.py 

### ISSUE THREAD

**Issue by yzho0907** [thunlp/JointNRE#7]
Some of flags below are not necessarily float! I have changed them to integers.

tf.app.flags.DEFINE_integer('nbatch_kg',100,'entity numbers used each training time')

tf.app.flags.DEFINE_integer('ent_total',lib.getEntityTotal(),'total of entities')
tf.app.flags.DEFINE_integer('rel_total',lib.getRelationTotal(),'total of relations')
tf.app.flags.DEFINE_integer('tri_total',lib.getTripleTotal(),'total of triples')
tf.app.flags.DEFINE_integer('katt_flag', 1, '1 for katt, 0 for att')

tf.app.flags.DEFINE_integer('max_length',config['fixlen'],'maximum of number of words in one sentence')
tf.app.flags.DEFINE_integer('pos_num', config['maxlen'] * 2 + 1,'number of position embedding vectors')
tf.app.flags.DEFINE_integer('num_classes', config['textual_rel_total'],'maximum of relations')

tf.app.flags.DEFINE_integer('hidden_size',230,'hidden feature size')
tf.app.flags.DEFINE_integer('pos_size',5,'position embedding size')

tf.app.flags.DEFINE_integer('max_epoch',30,'maximum of training epochs')
tf.app.flags.DEFINE_integer('batch_size',131*2,'entity numbers used each training time')

tf.app.flags.DEFINE_integer('test_batch_size',131*2,'entity numbers used each test time')

**Comment by THUCSTHanxu13** [comment]
I have fix flag's type in test.py
