### ISSUE TITLE
模型返回结果形式

### ISSUE THREAD

**Issue by liutianling** [thunlp/JointNRE#9]
使用训练好的模型做预测的时候输入输出是什么样的？
是不是这种组织形式：
输入是一句话，输出是一个三元组，（head, tail, relation）
或者是其他什么形式？
谢谢！

**Comment by THUCSTHanxu13** [comment]
输入是一句话以及两个标注出的实体，关系抽取部分的神经网络模型可以输出两个实体的关系。
